inherit_from: .rubocop_todo.yml

Layout/ClassStructure:
  Enabled: true
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 25

Style/AccessorGrouping:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/SpecialGlobalVars:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets

RSpec/ExampleLength:
  Max: 10
RSpec/ExpectChange:
  EnforcedStyle: 'block'
RSpec/IndexedLet:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 20
RSpec/NestedGroups:
  Max: 5

require:
  - rubocop-rspec
